{% set name = "igl" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geometryprocessing/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: 1e2446deeeb955e2e3e2a1e21de7428c9eeced29a5a4dae9d60cb386ba98186b

build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - libblas
    - libcblas
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.GPL
  summary: 'Simple python geometry processing library'
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/tutorial/
  dev_url: https://github.com/libigl/libigl/

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
