{% set name = "igl" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/geometryprocessing/libigl-python-bindings/archive/{{ version }}.tar.gz
  sha256: fa5c317c66be3f67a635bde1e5863e17bd024c02bc24c96949666c2b9deb885f

build:
  number: 0
  skip: True  # [py<31]
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - dlib  # [win]
  host:
    - python
    - pip
    - dlib  # [win]
    - libblas
    - libcblas
    - make
    - numpy=1.13
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - igl

about:
  home: https://libigl.github.io
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.GPL
  summary: 'Simple python geometry processing library'
  description: |
    libigl is a simple python and C++ geometry processing library.
    We have a wide functionality including construction of
    sparse discrete differential geometry operators and
    finite-elements matrices such as the cotangent Laplacian and
    diagonalized mass matrix, and
    simple facet and edge-based topology data structures.
  doc_url: https://libigl.github.io/tutorial/
  dev_url: https://github.com/libigl/libigl/

extra:
  recipe-maintainers:
    - teseoch
    - fwilliams
    - skoch9
    - danielepanozzo
